# Generated by Django 4.2.16 on 2026-05-14 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='isbn',
        ),
        migrations.RemoveField(
            model_name='libro',
            name='stock',
        ),
        migrations.AddField(
            model_name='libro',
            name='cupo',
            field=models.CharField(default=0, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='libro',
            name='curp',
            field=models.CharField(default='000000', max_length=18, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='libro',
            name='estatus',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('ENTREGADO', 'Entregado')], default='PENDIENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='libro',
            name='fecha_entrega',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='libro',
            name='localidad',
            field=models.CharField(default='000000', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='libro',
            name='municipio',
            field=models.CharField(default='000000', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='libro',
            name='periodo_entrega',
            field=models.CharField(default='000000', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='libro',
            name='programa',
            field=models.CharField(choices=[('RITA', 'Beca Rita Cetina'), ('BENITO', 'Beca Benito Juárez'), ('JEF', 'Jóvenes Escribiendo el Futuro')], default='000000', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='libro',
            name='autor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='biblioteca.autor', verbose_name='Responsable'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='biblioteca.categoria', verbose_name='Nivel Educativo'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='portada',
            field=models.ImageField(blank=True, null=True, upload_to='evidencias/', verbose_name='Evidencia de Entrega'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='titulo',
            field=models.CharField(max_length=200, verbose_name='Nombre del Beneficiario'),
        ),
    ]
