# Generated by Django 4.2.16 on 2026-05-14 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_remove_libro_isbn_remove_libro_stock_libro_cupo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='biblioteca.autor', verbose_name='Responsable'),
        ),
    ]
