# Generated by Django 6.0 on 2025-12-26 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_categoria_autor_nacionalidad_libro_descripcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
