# Generated by Django 4.2.16 on 2026-05-14 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0003_alter_libro_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='cct_escuela',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='CCT de la Escuela'),
        ),
        migrations.AddField(
            model_name='libro',
            name='id_tarjeta',
            field=models.CharField(blank=True, error_messages={'unique': 'Ya hay una tarjeta registrada con este ID.'}, max_length=50, null=True, unique=True, verbose_name='ID de Tarjeta'),
        ),
        migrations.AddField(
            model_name='libro',
            name='nombre_escuela',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Nombre de la Escuela'),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='moneda',
            field=models.CharField(default='$', max_length=5),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='nombre_institucion',
            field=models.CharField(default='Gestor Documental Empresarial', max_length=200),
        ),
        migrations.AlterField(
            model_name='libro',
            name='curp',
            field=models.CharField(error_messages={'unique': 'Ya hay una tarjeta asociada con esta CURP.'}, max_length=18, unique=True, verbose_name='CURP'),
        ),
    ]
