# Generated by Django 4.2.16 on 2026-05-15 02:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('biblioteca', '0004_libro_cct_escuela_libro_id_tarjeta_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='capturado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capturas_realizadas', to=settings.AUTH_USER_MODEL, verbose_name='Capturado por'),
        ),
        migrations.AddField(
            model_name='libro',
            name='fecha_captura_entrega',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Captura de Entrega'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='cupo',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('municipio_asignado', models.CharField(blank=True, max_length=150, null=True, verbose_name='Municipio Asignado')),
                ('cargo', models.CharField(blank=True, max_length=150, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
