# Generated by Django 6.0 on 2025-12-26 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0004_libro_portada'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='renovaciones',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
