# Generated by Django 6.0 on 2025-12-26 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0005_prestamo_renovaciones'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='multa',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
