# Generated by Django 4.2.16 on 2026-05-15 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0006_municipio_localidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='apellido_materno',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Apellido Materno'),
        ),
        migrations.AddField(
            model_name='libro',
            name='apellido_paterno',
            field=models.CharField(default='', max_length=150, verbose_name='Apellido Paterno'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='libro',
            name='nombre',
            field=models.CharField(default='', max_length=150, verbose_name='Nombre(s)'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='libro',
            name='titulo',
            field=models.CharField(blank=True, editable=False, max_length=300, verbose_name='Nombre Completo'),
        ),
    ]
