# Generated by Django 6.0 on 2025-12-26 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0007_reserva'),
    ]

    operations = [
        migrations.CreateModel(
            name='Configuracion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_institucion', models.CharField(default='Biblioteca Central', max_length=200)),
                ('tasa_multa_dia', models.DecimalField(decimal_places=2, default=2.5, max_digits=5, verbose_name='Costo Multa por Día')),
                ('dias_prestamo_defecto', models.IntegerField(default=7, verbose_name='Días de Préstamo (Default)')),
                ('moneda', models.CharField(default='S/.', max_length=5)),
            ],
        ),
        migrations.AlterField(
            model_name='reserva',
            name='estado',
            field=models.CharField(choices=[('P', 'Pendiente'), ('C', 'Completada'), ('X', 'Cancelada')], default='P', max_length=1),
        ),
    ]
