# Generated by Django 4.2.16 on 2026-05-16 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0007_libro_apellido_materno_libro_apellido_paterno_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracion',
            name='dias_prestamo_defecto',
        ),
        migrations.RemoveField(
            model_name='configuracion',
            name='moneda',
        ),
        migrations.RemoveField(
            model_name='configuracion',
            name='tasa_multa_dia',
        ),
        migrations.AddField(
            model_name='configuracion',
            name='cargo_responsable',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='color_principal',
            field=models.CharField(default='#0d6efd', max_length=20),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='color_secundario',
            field=models.CharField(default='#198754', max_length=20),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='logo_institucional',
            field=models.ImageField(blank=True, null=True, upload_to='configuracion/'),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='mensaje_bienvenida',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='meta_diaria_entregas',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='mostrar_ranking_productividad',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='municipio_sede',
            field=models.CharField(default='PAPANTLA', max_length=150),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='nombre_sare',
            field=models.CharField(default='SARE 3011 PAPANTLA', max_length=200),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='obligar_evidencia_entrega',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='configuracion',
            name='responsable_operativo',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='configuracion',
            name='nombre_institucion',
            field=models.CharField(default='Coordinación Nacional de Becas para el Bienestar', max_length=200),
        ),
    ]
