# Generated by Django 4.2.16 on 2026-05-17 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0008_remove_configuracion_dias_prestamo_defecto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='libro',
        ),
        migrations.RemoveField(
            model_name='reserva',
            name='usuario',
        ),
        migrations.DeleteModel(
            name='Prestamo',
        ),
        migrations.DeleteModel(
            name='Reserva',
        ),
    ]
