# Generated by Django 4.2.16 on 2026-05-17 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0009_remove_reserva_libro_remove_reserva_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='cupo',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True, verbose_name='Cupo asignado'),
        ),
    ]
