# Generated by Django 4.2.16 on 2026-05-17 20:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0011_programabeca'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='programa_beca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='expedientes', to='biblioteca.programabeca', verbose_name='Programa/Beca'),
        ),
    ]
