# Generated by Django 4.2.16 on 2026-05-17 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0012_libro_programa_beca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='categoria',
        ),
        migrations.AlterField(
            model_name='libro',
            name='programa',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
    ]
