# Generated by Django 4.2.16 on 2026-05-18 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0013_remove_libro_categoria_alter_libro_programa_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='libro',
            name='programa',
        ),
        migrations.CreateModel(
            name='Escuela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cct', models.CharField(max_length=30, unique=True, verbose_name='CCT')),
                ('nombre', models.CharField(max_length=250, verbose_name='Nombre de la Escuela')),
                ('nivel', models.CharField(choices=[('PREESCOLAR', 'Preescolar'), ('PRIMARIA', 'Primaria'), ('SECUNDARIA', 'Secundaria'), ('MEDIA_SUPERIOR', 'Media Superior'), ('SUPERIOR', 'Superior'), ('OTRO', 'Otro')], default='OTRO', max_length=30)),
                ('activo', models.BooleanField(default=True)),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escuelas', to='biblioteca.localidad')),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escuelas', to='biblioteca.municipio')),
            ],
        ),
    ]
