# Generated by Django 4.2.16 on 2026-05-18 17:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0014_remove_libro_programa_escuela'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='escuela',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='biblioteca.escuela', verbose_name='Escuela / CCT'),
        ),
    ]
