# Generated by Django 4.2.16 on 2026-05-19 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0015_libro_escuela'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='tipo_captura',
            field=models.CharField(choices=[('OPERATIVA', 'Operativa'), ('HISTORICA', 'Histórica')], default='OPERATIVA', max_length=20, verbose_name='Tipo de Captura'),
        ),
    ]
