# Generated by Django 4.2.16 on 2026-05-19 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0016_libro_tipo_captura'),
    ]

    operations = [
        migrations.AlterField(
            model_name='libro',
            name='curp',
            field=models.CharField(blank=True, error_messages={'unique': 'Ya hay una tarjeta asociada con esta CURP.'}, max_length=18, null=True, unique=True, verbose_name='CURP'),
        ),
    ]
