# Generated by Django 4.2.16 on 2026-05-20 04:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0017_alter_libro_curp'),
    ]

    operations = [
        migrations.CreateModel(
            name='CABB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=150)),
                ('responsable', models.CharField(blank=True, max_length=150, null=True)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='cabbs/')),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='localidad',
            name='cabb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='localidades', to='biblioteca.cabb'),
        ),
    ]
