# Generated by Django 4.2.16 on 2026-05-21 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0018_cabb_localidad_cabb'),
    ]

    operations = [
        migrations.AddField(
            model_name='libro',
            name='numero_tarjeta_bancaria',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True, verbose_name='Número de Tarjeta Bancaria'),
        ),
    ]
