# Generated by Django 4.2.16 on 2026-05-22 21:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('biblioteca', '0019_libro_numero_tarjeta_bancaria'),
    ]

    operations = [
        migrations.CreateModel(
            name='BitacoraMovimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('CREAR', 'Crear'), ('EDITAR', 'Editar'), ('IMPORTAR', 'Importar'), ('ENTREGAR', 'Entregar'), ('ELIMINAR', 'Eliminar'), ('ACTIVAR', 'Activar'), ('DESACTIVAR', 'Desactivar'), ('CURP', 'Actualizar CURP')], max_length=20)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('libro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='movimientos', to='biblioteca.libro')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Movimiento',
                'verbose_name_plural': 'Bitácora de Movimientos',
                'ordering': ['-fecha'],
            },
        ),
    ]
